# Generated by Django 5.0.6 on 2024-08-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('certificate_number', models.CharField(max_length=100)),
                ('completion_date', models.DateField()),
            ],
        ),
    ]
